name: navigation
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.0.0

  # Features
  cart:
    path: ../../feature/cart
  listing:
    path: ../../feature/listing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^2.8.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
