name: cart
description: "A module for managing the shopping cart."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  navigation_api:
    path: ../../core/navigation_api
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
